spring:
  application:
    name: tls-gateway
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://api:8080
          predicates:
            - Path=/api/**
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-alias: gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
